Análisis de correspondencias con R: aplicación a datos de encuestas
==============================================================

II Seminario Análisis de datos avanzados en Ciencias de la Salud, 
Facultad de Ciencias de la Salud de la Universidad Rey Juan Carlos,
Campus de Alcorcón.

Impartido por Emilio López Cano, 24 de mayo de 2018

Las diapositivas del seminario se encuentran en: http://emilio.lcano.com/p/seminariourjc18/

Preparando el entorno
-------------------------

Descarga e instala R y RStudio en tu sistema, y en ese orden. Puedes encontrar
las instrucciones y los archivos de instalación en las siguientes direcciones:

- http://www.r-project.org

- http://www.rstudio.com


Después de instalar R y RStudio, abre RStudio y ejecuta el siguiente
código en la consola de RStudio:

```{r, eval=FALSE}
install.packages(c("usethis", "readxl"))
usethis::use_course("")
```


En la consola se mostrarán mensajes de confirmación para descargar los materiales
en un fichero zip. Tras confirmar, el fichero se descarga y descomprime automáticamente
en la carpeta de usuario y se abre el proyecto RStudio con el que trabajaremos,
incluido código y datos.


Descripción e importación de datos
----------------------------------

```{r}
library(readr)
esudb16p <- read_csv("datos_2016/datos_ecv16/esudb16p.csv")
View(esudb16p)
```


